# Generated by Django 4.2.7 on 2023-12-08 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='input',
        ),
    ]
